#!/bin/bash

find . -name .DS_Store -exec rm -rf {} +
find . -name .env -exec rm -rf {} +
find . -name package-lock.json -exec rm -rf {} +
find . -name node_modules -type d -prune -exec rm -rf {} +
find . -name coverage -type d -prune -exec rm -rf {} +
